[project]
    name = "PyCatFile"
    version = "0.20.6"
    readme = "README.md"
    license = { text = "BSD-3-Clause" }
    keywords = []
    description = "A tar like file format name catfile after unix cat command (concatenate files) ."
    authors = [
        { name = "Kazuki Przyborowski", email = "kazuki.przyborowski@gmail.com" },
    ]
    