[project]
    name = "PyCatFile"
    version = "0.23.0"
    readme = "README.md"
    license = { text = "BSD-3-Clause" }
    keywords = []
    description = "A tar like file format name catfile after unix cat command (concatenate files) ."
    authors = [
        { name = "Kazuki Przyborowski", email = "kazuki.przyborowski@gmail.com" },
        { name = "Kazuki Suzuki Sadeghi", email = "kazuki.suzuki.sadeghi@gmail.com" },
        { name = "Game Maker 2k", email = "gamemaker2k@gmail.com" },
    ]
    